channels:
  - conda-forge
dependencies:
  # Base environment
  - python
  - pip
  # Jupyter
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-lsp
  - python-lsp-server
  - nbgitpuller
  # code-server
  - code-server
  - jupyter-vscode-proxy
  # Utilities
  - black
  - flake8
  - ipywidgets
  - nox
  - pre-commit
  - pytest
  # Main swarmpal dependencies
  - cartopy
  - dask
  - matplotlib
  - numpy
  - pandas
  - scipy
  - xarray
