#!/bin/bash
pip install https://github.com/smithara/apexpy/releases/download/v1.1.0-binaries/apexpy-1.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
git submodule update --init --recursive --remote
pip install -e SwarmPAL[dsecs,dev]

code-server --install-extension ms-python.python
jupyter lab workspaces import binder/default.jupyterlab-workspace
conda init
